export {default as Blog} from './Blog.vue'
export {default as Editor} from './Editor.vue'
export {default as Footer} from './Footer.vue'
export {default as Home} from './Home.vue'
export {default as Modal} from './Modal.vue'
export {default as Shop} from './Shop.vue'
export {default as Loading} from './Loading.vue'