export {default as Home} from './Home.vue'
export {default as Modal} from './Modal.vue'
export {default as Loading} from './Loading.vue'
export {default as Navbar} from './layout/Navbar.vue'
export {default as Footer} from './layout/Footer.vue'